### PR TITLE
Add UMD and package.json

### PR DESCRIPTION
**Pull request by eugef**
Script can be installed via npm and can be used with Node.js, RequireJS or directly in browser.

I found this script very useful but was unable easily install it via npm and use in Node.js.
This PR fixes the issue.

### CODE REVIEW

**Comment by albell** [comment]
Thanks, this is a really great idea. Much appreciated. Unfortunately I am a bit busy so I won't have time to review this until after the holidays. 

One quick question: why did you move the declaration of `collectCharacters()` inside the while loop? Seems cleaner/more efficient to declare once outside and reuse.

**Comment by eugef** [comment]
Hi @albell, it is an issue of the git diff.

I just wrapped your code in the [UMD template](https://github.com/umdjs/umd/blob/master/templates/returnExports.js) and removed references to the `window` object.

**Comment by albell** [comment]
Got it, yes the diff was a bit confusing on that point at first glance. Thanks for the contribution!

**Comment by eugef** [comment]
Great! 

Would be also nice to publish package on npm now.

**Pull request merged**
